//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeHause.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SaleProduct
    {
        public string Клиент { get; set; }
        public string Работник { get; set; }
        public System.DateTime Дата { get; set; }
        public int Количество { get; set; }
        public decimal Цена_покупки { get; set; }
    }
}
